## Numpy Functions

In [1]:
import numpy as np

In [8]:
a1=np.arange(12)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
a2=np.linspace(1,5,4)
a2

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [11]:
a1.reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a3=a1.reshape(2,2,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [18]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])