In [2]:
import numpy as np #importing the numpy module

In [7]:
n = int(input()) # asking user for the input and converting it into int datatype

3


In [12]:
x = np.arange(9) #getting evenly spaced values in the form of an array

In [13]:
print(x) #printing the array

[0 1 2 3 4 5 6 7 8]


In [15]:
x.reshape(n,n) #reshaping the array using the reshape inbuilt function

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
n = int(input()) #asking user for the input and converting it into int datatype

4


In [17]:
x = np.arange(16) #getting evenly spaced values in the form of an array

In [18]:
print(x) #printing the array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [19]:
x.reshape(n,n) #reshaping the array using the reshape inbuilt function

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])